<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="author" content="Cristina Barros Catalán" />
	<meta name="keywords" content="XHTML, web" />
	<meta name="description" content="Proyecto Datacleansing" />
	
	<link rel="stylesheet" type="text/css" href="css/estilo.css" title="Estilo principal"/>
	<script type="text/javascript" src="js/funciones.js"></script>
	
	<title>DataCleansing</title>
	
</head>
<body>
<div id="cuerpo">

	<div id="cabecera">
		<img border="0" src="img/logo.png" alt="Logo" width="400" height="50">
		
		<!--<h1>DataCleansing Project</h1>-->

	</div>

	