<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="author" content="Cristina Barros Catalán" />
	<meta name="keywords" content="XHTML, web" />
	<meta name="description" content="Proyecto Datacleansing" />
	
	<!--<link rel="stylesheet" type="text/css" href="css/plantilla1.css" title="Estilo principal"/>
	<link rel="alternate stylesheet" type="text/css" href="css/alternativa.css" title="Estilo alternativo" />
	<link rel="stylesheet" type="text/css" href="css/print.css" media="print" title="Estilo impresion"/>
	-->
	<script type="text/javascript" src="js/funciones.js"></script>
	
	<title>DataCleansing</title>
	
</head>
<body>

	<div id="cabecera">
	

	</div>